version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: local_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Kelechi52
      MYSQL_DATABASE: fineract
      MYSQL_USER: root
      MYSQL_PASSWORD: Kelechi52
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mysql_data:
