name: CI

on:
  push:
    branches: [main, orbit-haven]
  pull_request:
    branches: [main, orbit-haven]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Run build
        run: npm run build

      - name: Run Semgrep security scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

      - name: Smoke tests (optional)
        if: env.SUPABASE_SERVICE_ROLE_KEY != ''
        run: node scripts/smoke_tests.js
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
