name: Playwright E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
      NEXT_BASE_URL: http://localhost:3000
      SERVER_BASE_URL: http://localhost:5000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Seed server data
        run: node server/seed.js

      - name: Start backend server
        run: |
          nohup node server/server.js > server.log 2>&1 &
          echo $! > server.pid

      - name: Start Next.js app
        run: |
          nohup npm --prefix apps/web run dev > next.log 2>&1 &
          echo $! > next.pid

      - name: Wait for services
        run: |
          set -e
          echo "Waiting for backend..."
          for i in {1..60}; do
            if curl -sSf ${SERVER_BASE_URL}/api/health >/dev/null 2>&1; then
              echo "Backend ready"; break
            fi
            sleep 1
          done
          echo "Waiting for web..."
          for i in {1..60}; do
            if curl -sSf ${NEXT_BASE_URL} >/dev/null 2>&1; then
              echo "Web ready"; break
            fi
            sleep 1
          done

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Stop servers
        if: always()
        run: |
          set +e
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
          if [ -f next.pid ]; then kill $(cat next.pid) || true; fi
          pkill -f node || true
